### PR TITLE
Allow rule-making to affect multiple rules at once.

### PR DESCRIPTION
**Pull request by ojacobson**
This allows broadly the same kinds of changes (transmute, create, delete, or amend). I've flattened all kinds of amendment into a single "amend by changing" - suggestions welcome, though.

Because rules affected by a single rule change all receive the same number (rule -209), I've mandated the use of titles to render rules uniquely identifiable. A better rule-numbering system is probably required, and will likely be my next project once it's possible to change multiple rules at once.

Adding a title to this rule is permitted by rule -201, but is not required. It will be required, if and after this proposal is accepted.

This change satisfies rule -208: the nature of the change is explicit in the text of this proposal.

This change satisfies rule 1: it amends only rule 1, by modifying its text.

All other rules are trivially satisfied.

### CODE REVIEW

**Comment by bookofportals** [comment]
Don't like it. I agree with the principle, but find the language a bit... clunky. I'll vote in favor if you clean up the phrasing some. Definitely a good idea though. :smile:

**Comment by ojacobson** [comment]
Heh. I may have let my love of specificity get away from me. I'll see what I can do.

What sections (lord, there's a revealing question) need the most attention?

**Comment by bookofportals** [comment]
I may be a few hours responding. I have some work to do, and I need to think about it.

**Comment by bookofportals** [comment]
How is this?:

{
A rule-change (syn. proposal), affects one or more rules, including new rules not yet in existence, in exactly one way per rule.

Any existing rule may have its mutability changed from mutable to immutable or vice versa. Any existing rule may be retitled.

Any mutable rule may be:
* Repealed and removed from the rules, or

* Amended by changing either or both of its text or its title.

Any rule that does not yet exist may be enacted as a new mutable rule.

In addition, each affected rule must be given a title, if it does not already have one. (This type of retitling is different from the one above, and does not count as the one change of the rule. ) Each title must be distinct from the titles of all other rules currently in effect.The title of each rule should summarize the rule's subject matter.

A rule-change goes into effect the moment voting closes on the proposal. The changes to the rules are considered a single, indivisible event, even if the rule-change affects multiple rules.
}
I changed it in some substantive ways I consider minor. In addition, I would change the last paragraph to:
{
A rule-change goes into effect the moment voting closes on the proposal. The previous sentence notwithstanding, changes occur separately, each an infinitesimal period of time after the previous change, in the order in which they are written unless otherwise specified. (For these purposes, a change of title is a change.)
}

**Comment by ojacobson** [comment]
I'm not sure how I feel about sequencing rule-changes like that, given that "in the order written" is rather format-sensitive: does it mean the order they appear in the unified diff, or the order they are committed in in Git, or some other ordering? I'm not opposed to applying them in some sequence, given the right rationale, but I'd ideally like to be able to understand how to implement that sequence given Github's tooling (or, what's valuable about not using that tooling).

Otherwise, I really like that. I've adjusted my proposal accordingly. I've _not_ withdrawn and replaced it with a new proposal, so that the comment history is kept intact.

**Comment by bookofportals** [comment]
You're right, I'm still thinking by Agoran modes of thought. Which would you suggest? Unified diff?

**Comment by ojacobson** [comment]
Avoiding that question is part of my rationale for making the whole rule-change atomic 😁

However, if the elements of a change had to be sequenced, I'd probably prefer applying changes in diff order, one rule at a time, since that's the order players are going to be reading them in the majority of the time. That has some issues: transmuting a rule _and moving it in the document_ (as I did in #1) probably means that the rule is briefly ineffective, for example, since the whole-rule region of the diff where the rule is removed and the whole-rule region of the diff where the rule is replaced are separated by many other rules. An in-place modification of a rule in the middle, in the same proposal, could have Interesting results.

**Comment by bookofportals** [comment]
I think we shouldn't make the whole thing atomic (could get confusing, violates isolation). Don't know how to deal with it though.

**Comment by ojacobson** [comment]
That's fair.

I'm going to leave this in debate for tonight, and see if any of our other honourable players have any ideas.

**Comment by bookofportals** [comment]
Agreed. We'll what they think.

**Comment by bookofportals** [comment]
How about place in the unified diff, and original location for moves? Not very clean, but nobody's come up with a miraculous solution.

**Comment by ojacobson** [comment]
# The nature of a pull request

The underlying revision control system, Git, stores and communicates changes in terms of snapshots, not deltas. The tip of a proposal branch contains a full ruleset, and is complete on its own merits.

Both Git and Github tend to display that snapshot in terms of a diff against some prior state. For a proposal branch, the diff is against the last commit the branch has in common with `master` (by convention; there ain't no rule…). You can see that in effect by looking at this pull request's [Files Changed](/hubnomic/hubnomic/pull/2/files) tab.

The options for applying a proposal, packaged as a pull request, to the _text_ of the rules is to apply one of three computable algorithms, all three of which operate in terms of three-way merge (diff arithmetic, basically) under the hood.

The use of Github tools to process rules changes is not required by the rules. The use of Github, or a Git repository, to hold the canonical state of the rules is also not required by the rules.

# Personal thoughts

I want to use the framework of Nomic to explore two questions:

1. Can a revision control system be an effective way to communicate and version legislation-like things? Github (not Git, too primitive) has a lot of levers, and, in my professional life, I use them in lots of ways to work with structured rule-things. What about actual rules? In particular, how does the structure of Github’s communications framework affect the kinds of rules, and the kinds of enforcement mechanisms, that come about?

2. Are there more effective ways to structure Github-centric interactions that I can apply to software projects, that might become more apparent through a less casual, more formal approach? Nomic’s a good way to focus that intention, since the game and the medium are one and the same, whereas in most software projects the software is the end goal, and Github would be incidental were it not so central.

# Analysis

This is the first real proposal that's had to face the question of "how do we play Nomic on Github square on."

We have the option of ignoring Github entirely and treating it as a dumb repository of data about the game, in which case the structure of a pull request has no particular importance, and we can sequence side effects in any way we want. We also have the option of taking the effects of Github's workflow as-is, and adjusting the rules of the game to adapt to that medium. (In principle, we also have the option of adjusting Github's workflow, but without a collaborator on the inside, that option is inordinately difficult to exercise.)

In theory, Nomic's great strength as a tool for exploring the consequences of rules is in the game's fundamental mutability, but - for every Nomic I can find - some rules and customs are inevitably dependent on the underlying medium, be it note cards or email or a web site.

# Conclusion

I would prefer that we treat Github's workflow as a guiding force in the design of our rules-change process, at least for the time being, both because I am personally interested in doing so, and because I believe it's impractical to do otherwise while remaining on Github.

Therefore, I propose that compound rules-changes be a single event.

I open voting on this proposal as-is.

**Comment by bookofportals** [comment]
Moving. I vote FOR. :white_check_mark: Would you consider adding that to the Essays page on the wiki? I think it would be good to have saved, for the record. (Yeah, I know it already is, but I mean somewhere central and easily accessesable.)

**Comment by ojacobson** [comment]
Done! Somewhat clumsily, sorry about the history spam.

**Comment by bwarren2** [comment]
I am in FavOR :white_check_mark:

**Comment by wlonk** [comment]
FOR 👍

**Comment by mikejbrown** [comment]
:+1: (also :100: for eventual rule numbering reforms)

**Comment by ojacobson** [comment]
This proposal passes unanimously, scoring 11 points.

My score is now 21 points (applied in 4e63e631c942f8da8dd0ec3723fd37bc626cddc5).

**Pull request merged**
