### PR TITLE
Remove the mutable rule limit (rule -104)

### PR DESCRIPTION
**Pull request by bookofportals**
I don't see how the mutable rule limit serves any purpose. Having a limit of 25 mutable rules is just a barrier we're going to run into, so it makes sense to get rid of it.

### CODE REVIEW

**Comment by bookofportals** [comment]
By the way, I'm skipping the checklist. I don't think it's required, and it feels like a waste of time, so unless someone objects...

**Comment by ojacobson** [comment]
The checklist I've been using is certainly not required - I've been writing it out, one item at a time, as a crutch to make sure I don't skip any rules, not because I believe it's how we should all do things. For what it's worth, I believe this proposal can only pass unanimously, but I suspect that's obvious at this point, too.

I vote 👍.

I can only assume the 25-mutable-rule limit is useful for in-person games, if you're using index cards or something - either that, or it's meant to put pressure on players to complete multi-proposal projects.

**Comment by bookofportals** [comment]
I forgot to say this: I vote FOR. ✅

**Comment by bwarren2** [comment]
FOR :+1:

**Comment by wlonk** [comment]
FOR 👍 

@bookofportals I would assume that the person proposing a change is FOR 👍 anyway.

Also, I liked the checklist for the reasons @ojacobson listed; I find it personally useful.

**Comment by mikejbrown** [comment]
:+1:

**Comment by ojacobson** [comment]
Voting is unanimously in favour.

This proposal scores 14 points. @bookofportals' score is now 14 points (applied in a0fa642f37c2bea806d54c1661c5be0580900133).

**Pull request merged**
