### PR TITLE
Transmute rule -214 into a mutable rule.

### PR DESCRIPTION
**Pull request by ojacobson**
I intend to make it possible to amend more than one rule at a time. To do so, the rule allowing rule mutation must be modified, but that rule is currently immutable.

This change satisfies rule -214: it transmutes a single rule from immutable to mutable.

This change satisfies rule -209: the pull request implementing this rule has been numbered by Github.

This change satisfies rule -208: the nature of the change is explicit in the title of this proposal.

This change satisfies rule -211: the rules-change proposed is written down.

This change satisfies rule -104: there will be 13 mutable rules.

All other rules are trivially satisfied.

### CODE REVIEW

**Comment by wlonk** [comment]
I support this change, but the eventual goal (changing more than one rule at a time), is one I will have to evaluate when it is proposed.

**Comment by bookofportals** [comment]
I also support this, and will probably agree with the eventual goal, unless someone has some objection I haven't thought of. This is one of the more dangerous rules to play around with though, so any changes should be approached cautiously.

**Comment by ojacobson** [comment]
Nice work on labelling, @bookofportals.

As far as intent goes, I've gotten as far as something like

> A rule-change is any one of the following:
>
> 1. one or more changes to a mutable rule, where each change is either an enactment, a repeal, an amendment, or an amendment of an amendment, or
>
> 2. the transmutation of one or more immutable rules into mutables rules, or
>
> 3. the transmutation of one or more mutable rules into immutable rules.

(This is not a proposal, just a remark.)

However, I'd be in favour of a more structured way of changing rules so that the aggregate changes are atomic, and immutable rules are not left in a mutable state (either intentionally or accidentally).

**Comment by bookofportals** [comment]
Just to remind everyone, I don't think @ojacobson has brought this to a vote yet. Rule -206 is a bit vague, but I think it's best interpreted as "all proposals must be discussed before being voted upon". Calling for a vote probably just involves saying that you do. For voting, I suggest we use the convention FOR/AGAINST (from Agora). It's very unambiguous.

As for your draft, it should probably be "one or more of the following". At least I think that's what you're going for...

**Comment by mikejbrown** [comment]
Hi guys. Sorry for not taking part in the email thread - I've been under a rock for a week or so. I'm keen to see where this goes though.

As for voting, I think we could just use Github's :+1: / :-1:  or :white_check_mark: / :x:. There are also integrations which actually stop a PR from being mergeable unless there are enough approvals (e.g. https://github.com/integrations/lgtm and https://github.com/integrations/pullapprove). I have no personal experience with those but it could be an option.

For the record my vote is :+1: .

**Comment by ojacobson** [comment]
We should probably discuss form of voting and other mechanical changes in a proposal about voting!

Let's vote on this one. Per [the members list](https://github.com/orgs/hubnomic/people), I believe the current players are myself, @mikejbrown, @wlonk, and @bookofportals. Under rule -208, this proposal can only succeed if the vote is unanimously for it. Should we count votes of people who join while voting is ongoing?

I intend to count @mikejbrown's 👍 as a vote FOR this proposal. I also vote 👍 or FOR, and I would consider the two votes equivalent. The emoji reactions on this pull request suggest that @wlonk would also vote 👍 - the applicability of that vote is probably one for a voting proposal, though.

**Comment by wlonk** [comment]
Confirming that I do vote 👍 FOR.

**Comment by bookofportals** [comment]
I vote FOR. We can just leave voting up to individuals for now. Which means that it passes! I'll change it appropriately. In the long run, we should probably come up with membership methods that don't involve giving everyone that asks automatic write access, but that's a problem for another day... (Can you give someone read access to a public repository?)

**Comment by ojacobson** [comment]
This proposal scores one point.

My score is now 1.

**Comment by wlonk** [comment]
So, I'd like to point out that this was possibly passed and merged preemptively; as a proposal transmuting an immutable rule into a mutable rule, it should require a unanimous vote per rule -208. However, I'm not actually sure who the voters _were_ at the time this passed.

**Comment by bookofportals** [comment]
@wlonk, all eligible voters had voted for it at the time it was resolved. Our 5th player had not arrived, so the vote was valid.

**Comment by wlonk** [comment]
That's the crux of it—I wasn't clear on who was eligible at the time.

**Pull request merged**
