### PR TITLE
Streamline scoring algorithm.

### PR DESCRIPTION
**Pull request by bwarren2**
Slightly simplify scoring to streamline bookkeeping and promote focus on rules-matters.

### CODE REVIEW

**Comment by bookofportals** [comment]
Why not just repeal it? This seems clunky. AGAINST. ❌ As all votes must be unanimous, I could just fail this, but I'd like to see what the others think.

**Comment by bwarren2** [comment]
Mostly because I thought it was amusing.

**Comment by ojacobson** [comment]
Cute. I like the idea, but I, too, would have voted ❌  against on this one.

**Comment by ojacobson** [comment]
This proposal scores -10 points.

@bwarren2's score is now -10, scored in a7abb982c01a9810601a8c6ddf24becadcd004ca.

**Comment by bookofportals** [comment]
I dispute the validity of that action. (See #9)

**Comment by bookofportals** [comment]
My dispute is resolved. (Again, see #9)

**Pull request closed without merging**
