### PR TITLE
Transmute Rule -205 into a mutable rule

### PR DESCRIPTION
**Pull request by wlonk**
I intend to allow for better, or different, or simply _no_ means of winning. To do so, the rule controlling win states must be modified, but that rule is currently immutable.

This change satisfies rule 1: it transmutes a single rule from immutable to mutable.

This change satisfies rule -209: the pull request implementing this rule has been numbered by Github.

This change satisfies rule -211: the rules-change proposed is written down.

This change satisfies rule -104: there will be 14 mutable rules.

All other rules are trivially satisfied.

To pass, per Rule -208, support must be unanimous.

### CODE REVIEW

**Comment by bookofportals** [comment]
Looks good. :white_check_mark:

**Comment by ojacobson** [comment]
Looks good. 👍

Looking forward to the followup.

**Comment by bwarren2** [comment]
FOR :+1:

**Comment by wlonk** [comment]
Waiting on a vote from @mikejbrown.

**Comment by mikejbrown** [comment]
Sorry, didn't see a notification for the PR for some reason. :+1:

**Comment by ojacobson** [comment]
This proposal now conflicts - does fixing the proposal invalidate votes?

(@wlonk: don't forget to vote!)

**Comment by bookofportals** [comment]
No, fixing it shouldn't conflict. If you want to have a CFJ, you can, but I don't see the point. It's pretty clear that however Git works, our proposal system views proposals as changes. So I'd say the votes remain valid, out of convenience if nothing else. That said, I have an idea for dealing with this kind of thing. It'll be on the issues section soon...

**Comment by mikejbrown** [comment]
I think it depends on the scale of the fix. If it's something simple and obvious like a renumbering or something then that should be fine. If it actually changes the behaviour then it should definitely invalidate the votes. Admittedly there is a grey area, but thanks to git's perfect history tracking we can all see exactly what happened and roll it back if need be.

**Comment by bookofportals** [comment]
I second @mikejbrown. This probably isn't the best way to solve this particular situation, so I won't use it, but what do you all think of solving game changing interpretation issues by RFC? It's more democratic than a CFJ, and perhaps better suited for large scale issues. It'd be informal, but that's fine, and we can work it into the rules eventually.

**Comment by bookofportals** [comment]
And I think we can count @wlonk as having voted, based on their comments on #5. (which set of pronouns are we using? Should be gender neutral, but singular they or Spivak? The rules seem to use the singular they...)

Oh, and I'm getting my idea of RFCs from Wikipedia, just to make that clear.

**Comment by ojacobson** [comment]
> thanks to git's perfect history tracking we can all see exactly what happened and roll it back if need be.

I think this is core to any coherent application of Git or Github to rule-making. Thanks for bringing it up.

**Comment by bookofportals** [comment]
Apologies for tossing out a semi-formed idea with no context. My thinking was that some Nomics (BlogNomic, for one) judge CFJs by vote. I don't like the idea of a judicial system working by committee, so I thought that this might be an intermediate solution. Allow a consensus based approach for dealing with large-scale issues, and leave small scale stuff and final binding judgements to CFJs. Thoughts?

**Comment by wlonk** [comment]
Rebased, conflicts sorted. Problem with editing the end of the document.

I presumed my vote FOR 👍 was implicit in my putting forth the proposal! Well, I am FOR 👍 .

**Comment by bookofportals** [comment]
I think this is done? (the vote appears unanimous) I'd merge it myself, but for some reason I feel like I'm missing something... Probably just me being silly, but it never hurts to check.

**Comment by mikejbrown** [comment]
I'm happy. Merging anyway. Please revert if something's wrong.

**Comment by ojacobson** [comment]
Under the rules in effect when voting ended, this proposal scores 13 points for @wlonk (applied in f53374045f3f11ee8461c408a59e2bf5690ec44e).

**Pull request merged**
